// ES2021+ built-in globals (matches StandardJS environment)
export const BASE_GLOBALS = [
  'AggregateError',
  'Array',
  'ArrayBuffer',
  'Atomics',
  'BigInt',
  'BigInt64Array',
  'BigUint64Array',
  'Boolean',
  'DataView',
  'Date',
  'decodeURI',
  'decodeURIComponent',
  'encodeURI',
  'encodeURIComponent',
  'Error',
  'escape',
  'eval',
  'EvalError',
  'FinalizationRegistry',
  'Float32Array',
  'Float64Array',
  'Function',
  'globalThis',
  'Infinity',
  'Int16Array',
  'Int32Array',
  'Int8Array',
  'Intl',
  'isFinite',
  'isNaN',
  'JSON',
  'Map',
  'Math',
  'NaN',
  'Number',
  'Object',
  'parseFloat',
  'parseInt',
  'Promise',
  'Proxy',
  'RangeError',
  'ReferenceError',
  'Reflect',
  'RegExp',
  'Set',
  'SharedArrayBuffer',
  'String',
  'Symbol',
  'SyntaxError',
  'TypeError',
  'Uint16Array',
  'Uint32Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'undefined',
  'unescape',
  'URIError',
  'WeakMap',
  'WeakRef',
  'WeakSet',
  // Timers
  'queueMicrotask',
  'setTimeout',
  'clearTimeout',
  'setInterval',
  'clearInterval',
  'setImmediate',
  'clearImmediate',
  // Console
  'console',
  // Encoding
  'TextDecoder',
  'TextEncoder',
  // URL
  'URL'
]

export const HOLEPUNCH_GLOBALS = ['Pear', 'Bare']

export const ENV_GLOBALS = {
  node: [
    '__dirname',
    '__filename',
    'AbortController',
    'AbortSignal',
    'AsyncDisposableStack',
    'atob',
    'Blob',
    'BroadcastChannel',
    'btoa',
    'Buffer',
    'ByteLengthQueuingStrategy',
    'CloseEvent',
    'CompressionStream',
    'CountQueuingStrategy',
    'crypto',
    'Crypto',
    'CryptoKey',
    'CustomEvent',
    'DecompressionStream',
    'DisposableStack',
    'DOMException',
    'ErrorEvent',
    'Event',
    'EventTarget',
    'exports',
    'fetch',
    'File',
    'FormData',
    'global',
    'Headers',
    'localStorage',
    'MessageChannel',
    'MessageEvent',
    'MessagePort',
    'module',
    'navigator',
    'Navigator',
    'performance',
    'Performance',
    'PerformanceEntry',
    'PerformanceMark',
    'PerformanceMeasure',
    'PerformanceObserver',
    'PerformanceObserverEntryList',
    'PerformanceResourceTiming',
    'process',
    'ReadableByteStreamController',
    'ReadableStream',
    'ReadableStreamBYOBReader',
    'ReadableStreamBYOBRequest',
    'ReadableStreamDefaultController',
    'ReadableStreamDefaultReader',
    'Request',
    'require',
    'Response',
    'sessionStorage',
    'Storage',
    'structuredClone',
    'SubtleCrypto',
    'SuppressedError',
    'TextDecoderStream',
    'TextEncoderStream',
    'TransformStream',
    'TransformStreamDefaultController',
    'URLPattern',
    'URLSearchParams',
    'WebAssembly',
    'WebSocket',
    'WritableStream',
    'WritableStreamDefaultController',
    'WritableStreamDefaultWriter'
  ],
  browser: [
    'window',
    'document',
    'navigator',
    'location',
    'Audio',
    'MediaSource',
    'HTMLElement',
    'SVGElement',
    'EventTarget',
    'Node',
    'NodeList',
    'HTMLCollection',
    'MutationObserver',
    'requestAnimationFrame',
    'cancelAnimationFrame',
    'alert',
    'confirm',
    'requestAnimationFrame',
    'cancelAnimationFrame',
    'localStorage',
    'sessionStorage',
    'fetch',
    'Headers',
    'Request',
    'Response',
    'URL',
    'URLSearchParams'
  ],
  // ES2022-2024 are identical to ES2021 (already in BASE_GLOBALS)
  es2022: [],
  es2023: [],
  es2024: [],
  // ES2025+ additions
  es2025: ['Float16Array', 'Iterator'],
  es2026: ['Float16Array', 'Iterator']
}
